import 'dart:async';
import 'dart:convert';
import 'dart:isolate';

import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:restart_app/restart_app.dart';
import 'package:student/core/databases/server.dart';
import 'package:student/core/databases/shared_prefs.dart';
import 'package:student/ui/connect.dart';
// import 'package:student/core/databases/user.dart';

class Initializer extends StatefulWidget {
  const Initializer({super.key});

  @override
  State<Initializer> createState() => _InitializerState();
}

class _InitializerState extends State<Initializer> {
  final MobileScannerController controller = MobileScannerController(
    formats: [BarcodeFormat.qrCode],
    // required options for the scanner
  );

  void _handleBarcode(BarcodeCapture barcodes) {
    if (!mounted) return;

    Barcode? barcode = barcodes.barcodes.firstOrNull;
    if (barcode == null) return;

    Server.iCM.downloadFile(barcode.displayValue!).then((value) {
      Map<String, dynamic> parsed = jsonDecode(value.file.readAsStringSync());

      try {
        SharedPrefs.setString("env", parsed["env"]).then((_) {
          SharedPrefs.setString("user", parsed["user"]).then(
            (_) => Restart.restartApp(),
          );
        });
      } catch (e) {}
    });
  }

  @override
  Future<void> dispose() async {
    super.dispose();
    await controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        automaticallyImplyLeading: false,
        title: const Text("Scan code generated by the Extension"),
        centerTitle: true,
      ),
      body: Stack(children: [
        MobileScanner(
          controller: controller,
          // fit: BoxFit.contain,
          onDetect: _handleBarcode,
        )
      ]),
    );
  }
}
