import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:student/core/databases/server.dart';
import 'package:student/core/databases/shared_prefs.dart';
import 'package:student/ui/connect.dart';
// import 'package:student/core/databases/user.dart';

class Initializer extends StatefulWidget {
  const Initializer({super.key});

  @override
  State<Initializer> createState() => _InitializerState();
}

class _InitializerState extends State<Initializer> {
  // Barcode? _barcode;

  void _handleBarcode(BarcodeCapture barcodes) {
    if (!mounted) return;

    Barcode? barcode = barcodes.barcodes.firstOrNull;
    if (barcode == null) return;

    Server.iCM.downloadFile(barcode.displayValue!).then((value) {
      Map<String, dynamic> parsed = jsonDecode(value.file.readAsStringSync());

      SharedPrefs.setString("env", parsed["env"]).then((_) {
        SharedPrefs.setString("user", parsed["user"]).then(
          (_) => StudentApp.action(context, AppAction.init),
        );
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        automaticallyImplyLeading: false,
        title: const Text("Scan code generated by the Extension"),
        centerTitle: true,
      ),
      body: Stack(children: [
        MobileScanner(
          controller: MobileScannerController(
            formats: [BarcodeFormat.qrCode],
          ),
          fit: BoxFit.contain,
          onDetect: _handleBarcode,
        )
      ]),
    );
  }
}
